"""pysha-sdk: A Python SDK with Cython-optimized utilities."""

from pysha_sdk.utils.crypto import (
    calculate_md5_hash,
    encrypt_password,
    generate_random_id,
    generate_random_token,
    generate_unique_secure_token,
    hash_password,
    match_password,
    to_stable_uuid,
    uuidv7,
    uuidv7_to_datetime,
)
from pysha_sdk.utils.objects import (
    ChangeKeysCase,
    dict_or_pydantic_model_to_dict,
    find_subclasses,
    is_iterable_except_str_like,
    model_dump,
    recursive_sort_keys,
)
from pysha_sdk.utils.strings import (
    AnyStr,
    compounder,
    deburr,
    delimited_path_join,
    extract_digits,
    flatten_url_params,
    format_phone_number,
    from_base64,
    from_hex,
    has_unicode_word,
    is_ascii,
    is_base64,
    is_cron_expression,
    is_falsely,
    is_hebrew,
    is_hex,
    is_truthy,
    is_valid_email,
    is_valid_israeli_id,
    is_valid_phone_number,
    normalize,
    separator_case,
    slugify,
    to_ascii,
    to_base64,
    to_camel_case,
    to_constant_case,
    to_hex,
    to_kebab_case,
    to_pascale_case,
    to_plural,
    to_singular,
    to_snake_case,
    to_str,
    to_title_case,
    to_upper_first,
    to_url,
    words,
)

__all__ = [
    # String utilities
    "AnyStr",
    "compounder",
    "deburr",
    "delimited_path_join",
    "extract_digits",
    "flatten_url_params",
    "format_phone_number",
    "from_base64",
    "from_hex",
    "has_unicode_word",
    "is_ascii",
    "is_base64",
    "is_cron_expression",
    "is_falsely",
    "is_hebrew",
    "is_hex",
    "is_truthy",
    "is_valid_email",
    "is_valid_israeli_id",
    "is_valid_phone_number",
    "normalize",
    "separator_case",
    "slugify",
    "to_ascii",
    "to_base64",
    "to_camel_case",
    "to_constant_case",
    "to_hex",
    "to_kebab_case",
    "to_pascale_case",
    "to_plural",
    "to_singular",
    "to_snake_case",
    "to_str",
    "to_title_case",
    "to_url",
    "to_upper_first",
    "words",
    # Crypto utilities
    "calculate_md5_hash",
    "encrypt_password",
    "generate_random_id",
    "generate_random_token",
    "generate_unique_secure_token",
    "hash_password",
    "match_password",
    "to_stable_uuid",
    "uuidv7",
    "uuidv7_to_datetime",
    # Object utilities
    "ChangeKeysCase",
    "dict_or_pydantic_model_to_dict",
    "find_subclasses",
    "is_iterable_except_str_like",
    "model_dump",
    "recursive_sort_keys",
]


def main() -> None:
    """Main entry point for pysha-sdk."""
    print("Hello from pysha-sdk!")
